use spaces to indent

diff --git a/assets/setup/install b/assets/setup/install
--- a/assets/setup/install
+++ b/assets/setup/install
@@ -35,12 +35,12 @@ EOF
 timeout=120
 while ! mysqladmin -uroot status >/dev/null 2>&1
 do
-	timeout=$(expr $timeout - 1)
-	if [ $timeout -eq 0 ]; then
-		echo "Failed to start mysql server"
-		exit 1
-	fi
-	sleep 1
+  timeout=$(expr $timeout - 1)
+  if [ $timeout -eq 0 ]; then
+    echo "Failed to start mysql server"
+    exit 1
+  fi
+  sleep 1
 done
 
 # create user for the runner
